# This Docker Compose project is not intended to be executed directly.
# Instead, this project is meant to be merged with the `compose.base.yml`
# project.

version: "3"

services:
  exporter-service:
    env_file:
      - ./env/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8082:8082"
    volumes:
      - ./app:/app/app

  exporter-service-tests:
    env_file:
      - ./env/.env
    build: 
      context: .
      additional_contexts:
         common: ../common
      target: tests
    volumes:
      - ./reports:/app/reports

  