# This Docker Compose project is not intended to be executed directly.
# Instead, this project is meant to be merged with one of the
# `compose.production.yml` or `compose.standalone.yml` projects.

version: "3"

services:
  init-postgres:
    depends_on:
      - database-postgres
    build:
      context: .
      additional_contexts:
        common: ../../common
      dockerfile: Dockerfile
  database-postgres:
    image: postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 60s
      retries: 5