# This Docker Compose project is not intended to be executed directly.
# Instead, this project is meant to be merged with the `compose.base.yml`
# project.

version: "3"

services:
  database-postgres:
    env_file:
      - ./env/standalone.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5432:5432"
      
  init-postgres:
    env_file:
      - ./env/standalone.env
    extra_hosts:
      - "host.docker.internal:host-gateway"