version: "3.8"
services:
  db:
    build: .
    container_name: bdnr_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: bdnr_pgadmin
    depends_on:
      - db
    restart: always
    user: "${UID}:${GID}"
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - "./data/pgadmin:/var/lib/pgadmin"
