# This Docker Compose project is not intended to be executed directly.
# Instead, this project is meant to be merged with the `compose.base.yml`
# project.

version: "3"

services:
  database-mongo:
    image: europe-southwest1-docker.pkg.dev/weclarifai-420214/doclarifai/mongo:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
  # mongo-express:
  #   image: europe-southwest1-docker.pkg.dev/weclarifai-420214/doclarifai/mongo-express:latest
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"