# This Docker Compose project is not intended to be executed directly.
# Instead, this project is meant to be merged with the `compose.base.yml`
# project.

version: "3"

services:
  workflow-management-service:
    env_file:
      - ./env/standalone.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app/app