# This Docker Compose project is not intended to be executed directly.
# Instead, this project is meant to be merged with the `compose.base.yml`
# project.

version: "3"

services:
  workflow_management:
    env_file:
      - path: ./env/standalone.env
        required: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app/app
    environment:
      - PORT=8080

  tests:
    build: 
      context: .
      target: tests
    volumes:
      - ./reports:/app/reports

  