# This Docker Compose project is not intended to be executed directly.
# Instead, this project is meant to be merged with the `compose.base.yml`
# project.

version: "3"

services:
  authentication-service:
    env_file:
      - ./env/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8083:8083"
    volumes:
      - ./app:/app/app

  authentication-service-tests:
    build: 
      context: .
      target: tests
    volumes:
      - ./reports:/app/reports

  